title = "Leo Qin"
languageCode = "en"
theme = "smol"
preserveTaxonomyNames = true
copyright = "Leo Qin"

[outputs]
  home = ["HTML", "RSS"]

[params]
    dateFmt = "2006-01-02"

[permalinks]
  [permalinks.page]
    posts = '/posts/:slug/'
  [permalinks.section]
    posts = '/posts/'


[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "resume" # An unique identifier for the button
    name = "Resume"       # A display name for the button
    url = "/resume/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About This Blog"
    url = "/about-this-blog/"       # The path can lead to a content folder too.
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"       # The path can lead to a content folder too.
    weight = 40

[taxonomies]
category = "categories"
tags = "tags"
