---
kind: pipeline
type: docker
name: build

steps:
- name: build
  image: hugomods/hugo:latest
  commands:
  - hugo --config local
  when:
    event:
    - push
    - pull_request
    branch:
      exclude:
      - main