---
kind: pipeline
type: docker
name: branch_build

trigger:
  event:
  - push
  - pull_request
  branch:
    exclude:
    - main

steps:
- name: build
  image: hugomods/hugo:latest
  commands:
  - git submodule update --init --recursive
  - hugo --config local
  - hugo list all --config local
    