version: '3'

services:
  hugo:
    env_file: 
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HUGO_ENV: ${HUGO_ENV}
    ports:
      - 1313:80
    volumes:
      - ./:/src
